### ISSUE TITLE
Implement gaOptout() function

### ISSUE THREAD

**Issue by carlu93** [escopecz/grav-ganalytics#14]
Hi, thanks for the awesome plugin! :)
I'm just missing one little feature. In Germany we have to make sure the users can opt-out of GA.
In my understanding there has to be a function implemented in the GA Code.
Something like this:
function gaOptout() {
document.cookie = disableStr + '=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';
window[disableStr] = true;
}

Could you implement this for the plugin? Or am I missing something and this is already implemented?
Thanks a lot!

**Comment by TheMokke** [comment]
Hi,
from me too - thanks for this grav plugin. :)
But sadly I am also missing the gaOptout feature. 

Is is elementary for European users because of the new General Data Protection Regulation in Europe.

Please see https://webgilde.com/en/analytics-opt-out/ for the requirements.

**Comment by escopecz** [comment]
Implemented in https://github.com/escopecz/grav-ganalytics/pull/20, will be released soon.
