### ISSUE TITLE
GA in template?

### ISSUE THREAD

**Issue by elliotlewis** [escopecz/grav-ganalytics#15]
This might be a silly question but…

After installing the plugin and configuring, GA script does not appear in the site code. Are there extra steps to add this plugin to the site template?

**Comment by escopecz** [comment]
No, it will insert the tracking code no matter what template you use. The only option I can see while looking at the code is that maybe you are accessing from an IP address which you configured as blocked?

If not, please share your plugin configuration as a screenshot and give use a link to your website where the tracking should appear, but it does not.

**Comment by elliotlewis** [comment]
Unfortunately this is on an internal server so I can't send the link.
But I've identified the issue:
Selecting "Code Position" - `position: body` does not inject the code but `head` works.

**Comment by ViliusS** [comment]
@elliotlewis I have tested latest version with Quark and at least one more theme. It works with both, head and body positions.

If you still have issue feel free to reopen this ticket.
