### ISSUE TITLE
Is "do not track" respected by this plugin?

### ISSUE THREAD

**Issue by kees-closed** [escopecz/grav-ganalytics#19]
Some more info [here](https://www.analyticsmania.com/post/respect-do-not-track-parameter-google-tag-manager/). [Here](https://www.paulfurley.com/google-analytics-do-not-track/) is another example. Does this plugin support this as well?

**Comment by ViliusS** [comment]
No, it does not. Support for DNT header added in https://github.com/escopecz/grav-ganalytics/pull/36
