### ISSUE TITLE
IP Anonymization in Analytics

### ISSUE THREAD

**Issue by raum-IO** [escopecz/grav-ganalytics#2]
Full version: https://github.com/getgrav/grav-plugin-admin/issues/455

**Comment by escopecz** [comment]
Could you send a PR with your suggestions?

**Comment by Edelan** [comment]
Hello,

It is possible to modify the plugin to allow configuration of multiple subdomains.

like that for example:

<pre>
    trackingId:
      type: text
      size: medium
      label: Tracking ID
      placeholder: 'UA-...'
      help: Google Analytics tracking ID. In format UA-00000000-0.
    trackingSub:
      type: list
      label: Tracking subdomains
      fields:
        .url:
          type: text
          label: Subdomain URL
</pre>

https://support.google.com/analytics/answer/1034342?hl=en

Regards.
