### ISSUE TITLE
Grav 1.6 compatibility

### ISSUE THREAD

**Issue by drzraf** [escopecz/grav-ganalytics#22]
Just to be sure this does not get overlooked since Grav 1.6 is currently in -rc3.

**Comment by escopecz** [comment]
Please provide some details. This plugin is broken with 1.6-rc3? What is the error?

**Comment by ViliusS** [comment]
I'm closing this one due to no feedback. I'm running ganalytics plugin with 1.6 and 1.7 without issues.
