### ISSUE TITLE
on enabling my admin section hangs

### ISSUE THREAD

**Issue by captainandy14** [escopecz/grav-ganalytics#23]
on enabling ganalytics on grav quark open publishing, my admin side hangs with  A MASSIVE G ON IT...adding screenshot. Had to manually disable it by editing the yaml file.
![screenshot_ganalytics](https://user-images.githubusercontent.com/1235442/54928618-77d68b00-4f14-11e9-9319-8e3087f733a9.jpg)

**Comment by jleaders** [comment]
Do you have a modified twig template? It works for me with Quark

**Comment by ViliusS** [comment]
Cannot reproduce it either. Unless there is more information to work with, closing for now.
