### ISSUE TITLE
Any plans on GA4?

### ISSUE THREAD

**Issue by Karmalakas** [escopecz/grav-ganalytics#29]
Planning to implement [Google Analytics 4](https://support.google.com/analytics/answer/10089681)?

**Comment by escopecz** [comment]
I recently found out that I haven't check GA stats for several years and when I did I discovered I've never used this plugin I've created in my Grav based websites. So I'm thinking I won't spend time in this repository similarly like I should throw out the T-shirts I haven't wore for a year and use that space for stuff I use every day.

Want to be a maintainer?

**Comment by Karmalakas** [comment]
Let me get back to you on that in a few days, OK? :D My hands are full for now, but I'll still want to add GA, so might  take the deal ;)

**Comment by Coolguy3289** [comment]
Any updates on this? What about the changes made from #31 ?

**Comment by Karmalakas** [comment]
I'm still on old UA tracking and reviewed that PR. I just have no time now (and probably at least for a month more) to test it properly, but IMO this can't be merged.

**Comment by Coolguy3289** [comment]
Well the author closed the PR right after...Lovely

**Comment by Karmalakas** [comment]
I saw Google announced deadline for UA, so I will still need to migrate, but not sure if it will be PR for this plugin or I will simply hardcode the snippet. Or maybe I'll just create a separate simple plugin 🤔 Have lots of work at my full-time job and other more important side projects 🙂

**Comment by ViliusS** [comment]
I'm interested in this too. @Karmalakas did you investigate what needs to be done to prepare for GA4? Is it just a different tracking snippet, or other settings, like 'anonimizeIp', needs to be adjusted too?

Since UA will be sunset on 1st of July 2023 I think it is safe to change the plugin to handle ONLY GA4 at this point.

**Comment by Karmalakas** [comment]
Sorry, didn't look into it yet, but as deadline approaches, i guess I'll have to at some point 😅

**Comment by ViliusS** [comment]
I went ahead and made a PR https://github.com/escopecz/grav-ganalytics/pull/34

Still need to add UA -> GA4 update documentation and there is a nasty bug in Grav with Plugin:saveConfig(), but more or less it should work.
I have tried different cookie settings, renaming gtag object, the debug mode. The only thing I didn't test fully is opt-out mode.

Feel free to review and test.

**Comment by ViliusS** [comment]
UPDATE: added upgrade documentation to the PR.

The only issue to solve before PR can be merged is [this Grav bug](https://github.com/getgrav/grav/issues/3697).

**Comment by rodrigogiraoserrao** [comment]
@ViliusS could your PR be merged even with the linked issue still open?
The deadline for switching to GA4 is closing in and I don't mind doing a manual workaround to account for the linked issue. And I'm guessing others wouldn't mind, if that's what it takes for the Google Analytics plugin to have support for GA4.

**Comment by ViliusS** [comment]
@rodrigogiraoserrao yeah, I think it is better to have a working version with a documented known issue, than no version at all. I have pinged the author of this plugin to merge PR.

**Comment by escopecz** [comment]
Thanks folks! Merged.

**Comment by rodrigogiraoserrao** [comment]
Thanks @escopecz! How do we get this in the grav plugins?
You need to do a release, no?

**Comment by escopecz** [comment]
Yep. @ViliusS can you please check if you have permission to tag and release now?

**Comment by ViliusS** [comment]
@escopecz Thank you! Version 2.0.0 is now released and already synched with Grav servers.

If anyone finds issues with GA4 support, please open separate ticket for that.

**Comment by rodrigogiraoserrao** [comment]
Brilliant! Thank you both 😃
