### ISSUE TITLE
Allow subdomains

### ISSUE THREAD

**Issue by Edelan** [escopecz/grav-ganalytics#3]
Hello,

It is possible to modify the plugin to allow configuration of multiple subdomains.

like that for example:

<pre>
    trackingId:
      type: text
      size: medium
      label: Tracking ID
      placeholder: 'UA-...'
      help: Google Analytics tracking ID. In format UA-00000000-0.
    trackingSub:
      type: list
      label: Tracking subdomains
      fields:
        .url:
          type: text
          label: Subdomain URL
</pre>

https://support.google.com/analytics/answer/1034342?hl=en

Regards.

**Comment by Edelan** [comment]
Hi again,

I am not a developer, but I found this. This works, but I don't know if it's well written.

<pre>
    trackingId:
      type: text
      size: medium
      label: Tracking ID
      placeholder: 'UA-...'
      help: Google Analytics tracking ID. In format UA-00000000-0.
    trackingSub:
      type: array
      label: Subdomain url
      value_only: true
</pre>

then 

`$trackingSub = implode("','",($this->config->get('plugins.ganalytics.trackingSub')));`

and 

<pre>
...
    ga('create', '{$trackingId}', 'auto', {'allowLinker': true});
    ga('send', 'pageview');
    ga('require', 'linker');
    ga('linker:autoLink', ['{$trackingSub}'] );
</pre>

Can you tell if this is correct.

Regards.

**Comment by cworreschk** [comment]
Hi @Edelan 

What exactly do you want to configure?
The Link you've posted is about _cross domain tracking_ and not _multiple subdomains_.

**Comment by cworreschk** [comment]
Because of no response and the fact that tracking of subdomains can be configured in the GA backend I close this issue.
