### ISSUE TITLE
Class Zip Archive not found

### ISSUE THREAD

**Issue by fluidbrush** [escopecz/grav-ganalytics#6]
Got an error 'Class Zip Archive not found'.  Screenshot attached.

<img width="1391" alt="screen shot 2016-08-03 at 12 47 29 pm" src="https://cloud.githubusercontent.com/assets/801984/17357141/eba27f9c-5978-11e6-8616-d5713246f3ef.png">

**Comment by escopecz** [comment]
Install the PHP zip extension to your server or contact your hosting to do so for you.
